### ISSUE TITLE
Unable to access time2.ntfs.fn_<time>s

### ISSUE THREAD

**Issue by pidydx** [py4n6/pytsk#10]
When following these instructions to open a file on an ntfs image: https://github.com/py4n6/pytsk/wiki/Development
I am unable to access the ntfs times described in this document:
http://www.sleuthkit.org/sleuthkit/docs/api-docs/structTSK__FS__META.html

Is this not supported or what is the proper way to access those times?

**Comment by joachimmetz** [comment]
You'll have to provide much more detail here for me to be able to answer your question:

* what do the steps look in code you are doing?
* how do you open the file?
* what errors do you get? or what values doesn't the library give you?

**Comment by pidydx** [comment]
ntfs_dd.img is the file in the test_data dir of the GRR repo
import pytsk3
img = pytsk3.Img_Info(url="ntfs_dd.img")
volume = pytsk3.Volume_Info(img)
fs_offset = 63 * 512
fs = pytsk3.FS_Info(img, offset=fs_offset)
file_entry = fs.open("/Test Directory/notes.txt")
print file_entry.info.meta.time2.ntfs.fn_atime

This is what the TSK_FS_META seems to indicate it should be there, but I just get errors for those attributes not existing.  Using dir(file_entry.info.meta) doesn't seem to have the additional attributes where the NTFS times would be.

Bigger picture I am trying to fix the problem in GRR where it can't get all of the timestamps from Windows.  https://github.com/google/grr/pull/160

**Comment by joachimmetz** [comment]
I'm not sure if time2 is currently exposed in pytsk by the class parser. I'll have a look when time permits.

**Comment by pidydx** [comment]
Thanks!  Being able to get those times will be a significant benefit to GRR functionality when dealing with Windows.

**Comment by joachimmetz** [comment]
Some notes:
tsk/fs/tsk_fs.h:465
```
        /* filesystem specific times */
        union {
            struct {
...
        } time2;
```

time2 is a union with multiple file system dependent structs. For pytsk to handle these it would need to know the file system and determine which struct applies? or maybe exposes as is?

**Comment by joachimmetz** [comment]
class_parser.py:4106
```
        # Handle recursive struct or union definition (At the moment
        # we cant handle them at all)
        ["(RECURSIVE_)?STRUCT", "(struct|union)\s+([_A-Za-z0-9]+)?\s*{", "PUSH_STATE", "RECURSIVE_STRUCT"],
        ["RECURSIVE_STRUCT", "}\s+[0-9A-Za-z]+", "POP_STATE", None],
```

**Comment by joachimmetz** [comment]
So this functionality is not supported at the moment, for the main reason that it is  tricky to handle the union of structs correctly.

**Comment by joachimmetz** [comment]
A short term work around could be to get the NTFS attributes and parse them separately. Which is also technically more correct, since an MFT entry can contain more than 1 $FILE_NAME attribute.

Also see:
https://github.com/py4n6/pytsk/wiki/Development#accessing-a-alternate-data-stream-ntfs

**Comment by pidydx** [comment]
Is there a proper/sane way to do that in the context of GRR?  This is fundamentally what I am trying to fix: https://github.com/google/grr/pull/160

**Comment by joachimmetz** [comment]
I'm having a chat with @destijl about this next week. Basically every $FILE_NAME MFT attribute has 4 time stamps (which can be short filename, long filename, hard links) , and the corresponding $I30 $FILE_NAME entries (short filename, long filename) as well. Not sure if TSK provides easy access to the latter but the MFT attributes should be doable I think.

I guess the approach would be:
* get the file entry
* if file system is NTFS
  * get the attributes
  * parse the date and time values from the $FILE_NAME attributes
* report the file entry data back to the GRR server
* store the file entry data on the GRR server

Where I want to be able to get more attributes as well e.g. $OBJECT_IDENTIFIER

**Comment by pidydx** [comment]
Sounds good! The 8 timestamps of NTFS is the core of what I was trying to solve without having to do double file listings with GRR.  Python's stat only gets 3 when using OS so I figured the best thing to do is just get TSK to return all 8 as part of the stat of an NTFS file.

I will hold off on messing with this any more for the time being.

**Comment by joachimmetz** [comment]
Note that statement "the 8 timestamps of NTFS" is not a technically correct. As you can make up from my previous comment 8 timestamps (in the MFT entry) is the minimum, but can easily be 12 or more. If you include the timestamps in the directory index $I30 a "file entry" would have at minimum 12 timestamps and with a short and long file name at minimum 20 timestamps. Also see: https://github.com/libyal/libfsntfs/blob/master/documentation/New%20Technologies%20File%20System%20(NTFS).asciidoc

The TSK API (an therefore pytsk) tries hard to have NTFS look like EXT, which makes it IMO not the best solution for obtaining file system specific information.

**Comment by joachimmetz** [comment]
Closing issue, long term investment in pytsk does not seem effective use of resources

See https://github.com/sleuthkit/sleuthkit/issues/1002 for context
