### ISSUE TITLE
Add support to read attribute data

### ISSUE THREAD

**Issue by joachimmetz** [py4n6/pytsk#12]
Add support to read attribute data

**Comment by bobbypistol** [comment]
Any progress on this enhancement? I would love this

**Comment by joachimmetz** [comment]
Alas it sounds easier than implemented in the current version of sleuthkit. The challenge here is that [TSK_FS_ATTR](https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/tsk_fs.h#L284) does not offer a read and/or seek function. Also see: https://github.com/sleuthkit/sleuthkit/blob/develop/tsk/fs/tsk_fs_i.h#L88

This would mean that pytsk has to implement such a function itself, dealing with all the file system specific intricacies of reading attribute data.

**Comment by joachimmetz** [comment]
Closing issue, long term investment in pytsk does not seem effective use of resources

See https://github.com/sleuthkit/sleuthkit/issues/1002 for context
