### ISSUE TITLE
Python 3 support?

### ISSUE THREAD

**Issue by jovanni-hernandez** [py4n6/pytsk#13]
It appears that work began on supporting Python 3 with this library. Was this finalized? If not, are there any plans on doing so? I've tried the basic mmls example and it doesn't work in 3, but does in 2.7. 

Great work on putting this together, this is incredibly helpful for quickly doing FS forensics and automating repetitive tasks.

**Comment by joachimmetz** [comment]
> It appears that work began on supporting Python 3 with this library. Was this finalized?

https://github.com/py4n6/pytsk/issues/4

> I've tried the basic mmls example and it doesn't work in 3, but does in 2.7.

It might be that the example itself is not Python 3 compatible. Can you be more specific what doesn't work?

**Comment by jovanni-hernandez** [comment]
Thanks for the quick reply; the issue may just be me not understanding some python 3 concept. Here's the mmls example summarized:

```python
def mmlsExample(imageFile):
     img = pytsk3.Img_Info(imageFile)
     volume = pytsk3.Volume_Info(img)
     for part in volume:
          offset = part.addr * 512
          print(offset)
```

This example produces the starting byte offsets for each partition in the volume; it works as expected in 2.7. In 3.4, a type error is thrown:  `
TypeError: expected bytes, str found` at this line: `offset = part.addr * 512`

The pytsk3.TSK_VS_PART_INFO object seems to have different members on 2.7 vs 3.4 when I call dir() on it:

2.7:
```
['__class__', '__delattr__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__new__', '__nonzero__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'addr', 'desc', 'flags', 'len', 'next', 'prev', 'slot_num', 'start', 'table_num', 'tag', 'vs']
```

3.4:
```
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

Am I doing something silly?

**Comment by joachimmetz** [comment]
> The TSK_VS_PART_INFO object seems to have different attributes on 2.7 vs 3.4 when I call dir() on it:

That is correct.

>  TypeError: expected bytes, str

Would need to look into that, maybe an error in the bindings

**Comment by joachimmetz** [comment]
`TypeError: expected bytes, str found at this line: offset = part.addr * 512`

This is Python 3 being strict about string to byte conversions

**Comment by joachimmetz** [comment]
tests are passing with Python 3 also those of dfvfs https://travis-ci.org/log2timeline/dfvfs, which uses pytsk

Closing issue
