### ISSUE TITLE
MSVC files do not support building for 64 bit targets.

### ISSUE THREAD

**Issue by scudette** [py4n6/pytsk#14]
Please add a proper 64 bit target for VC solution.

**Comment by joachimmetz** [comment]
Why do you need this? I opt to use setup.py instead of the MSVC solution files directly.

Also VS 2008 express has not 64-bit support. 

Not sure 64-bit support in [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266)

**Comment by joachimmetz** [comment]
Should be solved by recent work on setup.py
