### ISSUE TITLE
Add support for unallocated space within volume.

### ISSUE THREAD

**Issue by dc3-plaso** [py4n6/pytsk#19]
I would like to be able to access the unallocated space within each volume. This could be done by exposing the [blockwalk](http://www.sleuthkit.org/sleuthkit/docs/api-docs/4.3/classTskFsInfo.html#a1ef0f35d665d6b8e653e3f60ab1f463b) function within sleuthkit.

**Comment by joachimmetz** [comment]
This is easier said than done, callback functions `a_action` are tricky to bind correctly.
```
uint8_t TskFsInfo::blockWalk	(	TSK_DADDR_T 	a_start_blk,
TSK_DADDR_T 	a_end_blk,
TSK_FS_BLOCK_WALK_FLAG_ENUM 	a_flags,
TSK_FS_BLOCK_WALK_CPP_CB 	a_action,
void * 	a_ptr 
)		
```

**Comment by sammy-tam** [comment]
is there any known workaround/alternative to this? trying find a solution to zero out unallocated blocks (without mounting the image).

**Comment by joachimmetz** [comment]
@sammy-tam you could use blockwalk instead

**Comment by sammy-tam** [comment]
thanks @joachimmetz. sorry but is the block walk function accessible via this python bindings? Doesn't seem like its a property under the FS_Info object. thanks

**Comment by joachimmetz** [comment]
> sorry but is the block walk function accessible via this python bindings?

No it is not, and unlike going to be unless the libtsk API+ABI improves, but you could use libtsk directly instead.

**Comment by sammy-tam** [comment]
got it thanks

**Comment by joachimmetz** [comment]
Closing issue, long term investment in pytsk does not seem effective use of resources

See https://github.com/sleuthkit/sleuthkit/issues/1002 for context
