### ISSUE TITLE
Ewf image with only a partition

### ISSUE THREAD

**Issue by bobbypistol** [py4n6/pytsk#20]
I have a ewf partition image (not a whole disk image). When trying to mount it i'm getting the following error, the image works in FTK. I added the script, am I missing here something?

> IOError: FS_Info_Con: (tsk3.c:207) Unable to open the image as a filesystem: Invalid magic value (Not a NTFS file system (magic)

[script.txt](https://github.com/py4n6/pytsk/files/197292/script.txt)

**Comment by joachimmetz** [comment]
```
        super(ewf_img_info, self).__init__(
            url="", type=pytsk3.TSK_IMG_TYPE_EWF_EWF)
```

This assumes pytsk with built-in EWF support, try `pytsk3.TSK_IMG_TYPE_EXTERNAL` instead. Also see: https://github.com/libyal/libewf/wiki/Development#combining-pyewf-with-pytsk3

**Comment by joachimmetz** [comment]
No update from OP closing issue.
