### ISSUE TITLE
Question on performance 

### ISSUE THREAD

**Issue by dnides** [py4n6/pytsk#21]
On windows, running Python 2.7 and pytsk3 version 20140506 opening a file entity is slow on the order of 2 – 4 seconds. The fs_info object is for an active drive. We have tried directly opening the entity using fs_info.open and fs_info.open_dir with similar results. Is there a more performant option to opening directories when traversing a directory tree? Are these times abnormal?

**Comment by joachimmetz** [comment]
> Are these times abnormal?

This depends on many factors, I opt to compare with fls

**Comment by joachimmetz** [comment]
closing issue, no updates from original reporter
