### ISSUE TITLE
Windows build fatal error

### ISSUE THREAD

**Issue by zachking** [py4n6/pytsk#22]
I followed the build instructions on the wiki and ran `python setup.py build`

**Here's the error:**
```
running build
running build_ext
Generating bindings...
Generating Python bindings for module pytsk3 from ['sleuthkit/tsk\\libtsk.h', 'sleuthkit/tsk\\base\\tsk_base.h', 'sleuthkit/tsk\\fs\\tsk_fs.h', 'sleuthkit/tsk\\img\\tsk_img.h', 'sleuthkit/tsk\\vs\\tsk_vs.h', 'tsk3.h']
error: [Errno 2] No such file or directory: 'sleuthkit/tsk\\libtsk.h'
```
I have Microsoft Visual Studio 2010 and Python 2.7.12 installed on my Windows 7 x64 computer.

It seems suspicious that the paths mix together "/" and "\\". Might this be the issue?

Thanks.

**Comment by joachimmetz** [comment]
Which version of pytsk?

**Comment by zachking** [comment]
I downloaded the code from the [repo](https://github.com/py4n6/pytsk) earlier today (7/28/2016).

**Comment by joachimmetz** [comment]
How? did you download it? from https://github.com/py4n6/pytsk/releases?

Did you download pytsk3-20160721.tar.gz or the github generated pytsk-20160721.zip or pytsk-20160721.tar.gz ?

The latter 2 are an annoying github feature that cannot be turned off and do not contain all the necessary files, so use the former.

**Comment by zachking** [comment]
Ah okay, yeah I just downloaded pytsk3-20160721.tar.gz, and it worked perfectly. I think I had downloaded the pytsk-20160721.zip at first. I just assumed that zip meant it was probably for Windows.

Maybe if there was a direct link to the correct download from the README, instead of a link to the releases page, it would cause much less confusion.

Thanks for the quick reply.

**Comment by joachimmetz** [comment]
We'll update the doc to be more explicit but you'll not be the last to run into this problem, the best way forward is to reach out to github and mention the defect in their UX.

**Comment by joachimmetz** [comment]
Updated the documentation a bit.
