### ISSUE TITLE
Array support in class_parser

### ISSUE THREAD

**Issue by veyesecurity** [py4n6/pytsk#23]
Hello,
Seems that you lack support for arrays in your struct parser.
For example:
https://github.com/sleuthkit/sleuthkit/blob/200d914985a4b9593588492624cadec1f43fd1e8/tsk/fs/tsk_fs.h#L917

```
struct TSK_FS_INFO {
...
uint8_t fs_id[TSK_FS_INFO_FS_ID_LEN];
...
```

fs_id field is not available in python representation of TSK_FS_INFO struct.

**Comment by veyesecurity** [comment]
We would like to use this feature in one of our projects. Could you please give us an ETA for the "enhancement" so we'll plan according to it.
Thanks

**Comment by joachimmetz** [comment]
> Could you please give us an ETA for the "enhancement" so we'll plan according to it.

I cannot, if it is urgent I opt to add it yourself and contribute it to the project.

**Comment by joachimmetz** [comment]
Closing issue, long term investment in pytsk does not seem effective use of resources

See https://github.com/sleuthkit/sleuthkit/issues/1002 for context
