### ISSUE TITLE
Add support to interact with metadata files e.g. VSS

### ISSUE THREAD

**Issue by dnides** [py4n6/pytsk#26]
It appears support was added into TSK. 

https://github.com/sleuthkit/sleuthkit/issues/466

Can we get it exposed please into pytsk when time permits.

**Comment by dnides** [comment]
@joachimmetz Do you know by chance if this if fixed by sleuthkit 4.4.0? Looks like that issue is fixed but not sure if the support translated into the pytsk bindings with your latest release. Thx.

**Comment by joachimmetz** [comment]
pytsk was recently updated to 4.4.0 but I've had not have the time to look into what needs to be changed.

**Comment by joachimmetz** [comment]
Pytsk was updated to sleuthkit 4.4.1 try if this is working as expected now

**Comment by joachimmetz** [comment]
Closing issue, long term investment in pytsk does not seem effective use of resources

See https://github.com/sleuthkit/sleuthkit/issues/1002 for context
