### ISSUE TITLE
FLS -l option

### ISSUE THREAD

**Issue by Ivano33** [py4n6/pytsk#27]
Hi,

do you have the FLS -l option planned like mentioned in the example?
It would come in handy for me.

Greets

**Comment by joachimmetz** [comment]
The fls example can be found here: https://github.com/py4n6/pytsk/blob/master/examples/fls.py

If it is not in there then no.

**Comment by Ivano33** [comment]
Technically it's in there :)

```
# TODO: not implemented.
  # args_parser.add_argument(
  #     "-l", dest="long_listing", action="store_true", default=False,
  #     help="Display long version (like ls -l)")``
```

**Comment by joachimmetz** [comment]
Yeah, but there does not seems to be code that actual prints a long listing

**Comment by Ivano33** [comment]
Alright, well thanks for the quick replies!

Have a good day :)
