### ISSUE TITLE
Reading alternate data streams

### ISSUE THREAD

**Issue by tincho9** [py4n6/pytsk#34]
Hi,
According to the documentation in https://github.com/py4n6/pytsk/wiki/Development, 
once we have the `ads_attribute`, we can read the file using:
`file_entry.read_random(offset, size, ads_attribute.info.type, ads_attribute.info.id)` 
I could not understand how can I get the relevant offset and size. 

Best Regards,
Martin.

**Comment by joachimmetz** [comment]
> I could not understand how can I get the relevant offset and size.

Not sure sure what you mean, these are the offset and size of the data you want to read.

**Comment by tincho9** [comment]
How can I get the offset where the alternate data stream content starts?

**Comment by joachimmetz** [comment]
The contents is describe by data runs of the NTFS DATA attribute of the ADS (which can also be compressed). Why would you want to know the offset of the fist data run?

(read_random allows you to read the contents of the ADS, it reconstructs the data runs for you)

**Comment by joachimmetz** [comment]
> If I understand correctly the offset it the offset of the file itself then?

I'm not sure what you mean / asking me

The offset passed to read_random is the offset in the data of the contents of the data stream (file/ADS) 

> How can I get the offset and the size?

Of what the data stream (file/ADS) ? or the NTFS $DATA attribute?

**Comment by tincho9** [comment]
For example, I want to extract the usnjournal, which is at `$Extend\$UsnJrnl:$j`. 
I have the file object referring to $UsnJrnl (A TSKFileEntry). How do I go from there?

**Comment by joachimmetz** [comment]
I think this answers your question: https://github.com/py4n6/pytsk/wiki/Development#accessing-a-alternate-data-stream-ntfs. If not let me know.

**Comment by tincho9** [comment]
Again, this is the documentation I was using, but I do not understand from where the `offset, size` variables came.

**Comment by joachimmetz** [comment]
these do not come from anywhere these are the size of the data to read from the data stream and the offset (relative from the start) in the data stream to start reading from. Very similar to the pread function on Linux.

**Comment by tincho9** [comment]
relative to the start of the file itself? And how can that offset and the size of the ADS?

**Comment by joachimmetz** [comment]
So file is a convoluted term to use here (hence data stream), but if you mean ADS with file then yes.

> And how can that offset and the size of the ADS?

Unclear to me what you are asking here?

read the first 10 bytes for the ADS
```
read_random(0, 10, ...)
```

read the next 10 bytes for the ADS
```
read_random(10, 10, ...)
```

etc

**Comment by tincho9** [comment]
What I mean is that your example is incomplete. 
```
file_entry.read_random(offset, size, ads_attribute.info.type, ads_attribute.info.id)
```

This is the first time the offset and size variables are mentioned, Where did you declare them?

**Comment by joachimmetz** [comment]
why does the example need to define them?

**Comment by tincho9** [comment]
I didn't understand how did you get the offset and the size of the ADS, that's all.

**Comment by joachimmetz** [comment]
> I didn't understand how did you get the offset and the size of the ADS, that's all.

these are not the offset and the size **of** the ADS but the offset and the size **in** the ADS

**Comment by tincho9** [comment]
Thanks, Managed to extract the ADS
The offset was `ads_attribute.info.fs_file.fs_info.offset` and the size was `ads_attribute.info.size`. 
Thanks
