### ISSUE TITLE
config.status: error: Something went wrong bootstrapping makefile fragments on Alpine Linux

### ISSUE THREAD

**Issue by trytr32** [py4n6/pytsk#39]
Hello,

I am having some trouble installing the latest version on pytsk3 on a alpine Docker image

>     config.status: error: in `/tmp/pip-install-ex4faq8w/pytsk3/sleuthkit':
>     config.status: error: Something went wrong bootstrapping makefile fragments
>         for automatic dependency tracking.  Try re-running configure with the
>         '--disable-dependency-tracking' option to at least be able to build
>         the package (albeit without support for automatic dependency tracking).

I have attached an example of how to reproduce the problem, but basically it shows:
* fire up an alpine docker container
* install a few deps pytsk3 needs
* try install latest pytsk3 (with failure)
* try install last version of pytsk3 (with success)

[example.txt](https://github.com/py4n6/pytsk/files/2749451/example.txt)

**Comment by joachimmetz** [comment]
Can you attach the config.log created in the sleuthkit sub directory.

**Comment by joachimmetz** [comment]
```
config.status:22449: cd tsk/base       && sed -e '/# am--include-marker/d' Makefile         | make -f - am--depfiles
./config.status: line 1: make: not found
```

do you have make installed?

**Comment by trytr32** [comment]
No I didn't, I just tested it again with it installed and it works fine now.  Thank you for your help!

**Comment by joachimmetz** [comment]
This Python binding needs make. Issue seems addressed, closing
