### ISSUE TITLE
Undefined symbol libvmdk_handle_read_buffer_at_offset

### ISSUE THREAD

**Issue by Sim4n6** [py4n6/pytsk#40]
When I import pytsk3, I get this error message : 
`ImportError: /usr/local/lib/python3.7/site-packages/pytsk3-20190304-py3.7-linux-x86_64.egg/pytsk3.cpython-37m-x86_64-linux-gnu.so: undefined symbol: libvmdk_handle_read_buffer_at_offset
`
I build/install pytsk from HEAD of git repo OR from pypi same error happens.

I am working on Debian all dependencies seems to be installed. I also install libvmdk-dev unstable version (latest) using apt.

**Comment by joachimmetz** [comment]
sleuhtkit configure likely detects libvmdk and included headers on your build system but is unable to find the library. Try adding `--without-libvmdk` to setup.py. Also see: https://github.com/py4n6/pytsk/blob/master/setup.py#L210

**Comment by joachimmetz** [comment]
I've added the changes to HEAD https://github.com/py4n6/pytsk/commit/b7e05e181b09c154d3b78ae219c7ec0bb60b3a4d

**Comment by Sim4n6** [comment]
It is working now, thank you @joachimmetz

**Comment by joachimmetz** [comment]
@Sim4n6 I assume the thumbs up means that solved the issue?

**Comment by joachimmetz** [comment]
the magic of concurrency ;)
