### ISSUE TITLE
Does pytsk have support for tsk_fs_dir_walk (and equivalent)?

### ISSUE THREAD

**Issue by Tartori** [py4n6/pytsk#46]
I'm using pytsk3 to scan all files and directories on a file image. To do that with pytsk3 I can only open the root directory and then from there scan each directory. This takes a longer time than tsk could do by default with functions like tsk_fs_dir_walk. Are they available through pytsk3 and I just didn't find it?

**Comment by joachimmetz** [comment]
> Are they available through pytsk3 and I just didn't find it?

These are not there. If you want to implement this functionality you'll need to create something to have the C function callback (TSK_FS_DIR_WALK_CPP_CB) callback into your Python callback function.

**Comment by Tartori** [comment]
Thanks for the fast answer. I will consider adding the functionality in the future. For now the existing functionality works for me. Should we close this issue because the question has been answered?
