### ISSUE TITLE
cannot find -ltalloc

### ISSUE THREAD

**Issue by odibrowne** [py4n6/pytsk#6]
I am attempting to install pytsk onto my debian computer but I keep getting the following

Sleuthkit headers found in: /usr/include
Sleuthkit version found: 4.1.3
Pytsk version found: 20150111
/usr/bin/ld: cannot find -ltalloc
collect2: error: ld returned 1 exit status

Any advice would be appreciated

**Comment by ajnelson** [comment]
Are either of the packages `python-talloc` or `python-talloc-dev` installed?  (At least, those are the names in Ubuntu.  Do they exist in Debian?  `talloc` doesn't exist in Ubuntu.)

**Comment by joachimmetz** [comment]
```
/usr/bin/ld: cannot find -ltalloc
collect2: error: ld returned 1 exit status
```
This is just setup.py not detecting a usable libtalloc often caused by a missing libtalloc-dev. pytsk will fall back to the version of talloc it comes with.
