### ISSUE TITLE
Recursing through directories with pytsk3.Directory or pytsk3.FS_Info object

### ISSUE THREAD

**Issue by chapinb** [py4n6/pytsk#7]
I do apologize if I have missed this while reviewing the documentation or samples, though if I have, could you direct me to the correct location and I will be happy to take up little of your time!

I have successfully set up pytsk3 to read the image, and following the steps in the wiki, in addition to the documentation & self-exploration, I was curious if there was a pre-built method to have pytsk3 recurse through the image with a for loop, in example.

I currently have a for loop set up on the `pytsk3.Directory` object and I am able to read the information about the items in the base directory, though I would also like to crawl the subdirectories autonomously and get information from them & their contents. 

Here is the code snippet:

![image](https://cloud.githubusercontent.com/assets/7152035/5993871/6f24e5a6-aa2c-11e4-95fd-7ea453f59510.png)

Here is the sample output:

![image](https://cloud.githubusercontent.com/assets/7152035/5993884/ca4c6cc4-aa2c-11e4-9fca-482a71e8b8e9.png)

Thanks in advance, and please let me know if any additional information/clarification is needed!

**Comment by joachimmetz** [comment]
Have a look at: https://github.com/py4n6/pytsk/blob/master/samples/fls.py

**Comment by joachimmetz** [comment]
No response from OP, assuming question is answered.
