### ISSUE TITLE
Is there anyway to iterate files in a live system?

### ISSUE THREAD

**Issue by desegel** [py4n6/pytsk#8]
Hi, is there any way to use your library to iterate and read files from a live NTFS system?
All of the examples and documentations require a raw image file, not devices like \\.\HardDisk0 etc..

Thanks so much.

**Comment by joachimmetz** [comment]
So Windows has a lot of variations of "device file names" and devices. I assume with " \.\HardDisk0" you mean "\\.\PhysicalDrive0" which should be directly supported by the SleuthKit and thus by pytsk.

Technically a storage media device is a RAW storage media image. But be aware that while analyzing a live file system the structures can change while analyzing.

An alternative solution you could use is e.g. [libsmdev](https://github.com/libyal/libsmdev)
