### ISSUE TITLE
OverflowError when reading ADS with read_random()

### ISSUE THREAD

**Issue by 6adir123** [py4n6/pytsk#98]
hello
after running **file_handle.read_random(0, attribute.info.size, attribute.info.type, attribute.info.id)**
(trying to extract an ADS attribute from a file in NTFS)
I got an **OverflowError: Python int too large to convert to C long**

Is there any solution to this problem?

**Comment by joachimmetz** [comment]
what values are you passing? do you use a 32-bit or 64-bit build?

**Comment by 6adir123** [comment]
Hi the issue was resolved
Thank you for your help (the file was too big to extract)
